# Generated by Django 2.1.3 on 2018-12-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('mobile_num', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FlightInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.CharField(max_length=12)),
                ('depart', models.DateField()),
                ('r_date', models.DateField()),
                ('from_city', models.CharField(max_length=20)),
                ('to_city', models.CharField(max_length=20)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.CharField(max_length=12)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('city', models.CharField(max_length=20)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.CharField(max_length=12)),
                ('depart', models.DateField()),
                ('r_date', models.DateField()),
                ('from_city', models.CharField(max_length=20)),
                ('to_city', models.CharField(max_length=20)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
            ],
        ),
    ]
