# Generated by Django 2.1.3 on 2018-12-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181226_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=250)),
                ('package_image', models.ImageField(upload_to='website/media')),
                ('package_day', models.IntegerField(blank=True, null=True)),
                ('package_night', models.IntegerField(blank=True, null=True)),
                ('package_price', models.IntegerField(blank=True, null=True)),
                ('package_category', models.CharField(max_length=60)),
            ],
        ),
    ]
