# Generated by Django 2.1.3 on 2018-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_visainquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=60)),
                ('p_mobile', models.IntegerField(blank=True, null=True)),
                ('p_email', models.EmailField(max_length=20)),
            ],
        ),
    ]
