# Generated by Django 2.1.3 on 2018-12-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_domestic_package_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='camping',
            name='package_itinerary',
            field=models.FileField(default='website/itinerary/newbalaji.pdf', upload_to='website/itinerary'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='package_itinerary',
            field=models.FileField(default='website/itinerary/newbalaji.pdf', upload_to='website/itinerary'),
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='package_itinerary',
            field=models.FileField(default='website/itinerary/newbalaji.pdf', upload_to='website/itinerary'),
        ),
        migrations.AddField(
            model_name='international_package',
            name='package_itinerary',
            field=models.FileField(default='website/itinerary/newbalaji.pdf', upload_to='website/itinerary'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='package_itinerary',
            field=models.FileField(default='website/itinerary/newbalaji.pdf', upload_to='website/itinerary'),
        ),
    ]
